branches:
  only:
    - main

jobs:
  include:
    - language: java
      jdk: openjdk17
      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.gradle'
      install:
        - chmod +x gradlew
      script:
        - ./gradlew clean build

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ktw550111@gamil.com