version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/step2/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  commands:
    pre_build:
      - chmod +x scripts/deploy.sh
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root